// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/dump.proto

package dumpproto // import "github.com/moooofly/opencensus-go-exporter-agent/gen-go/dumpproto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import metricsproto "github.com/census-instrumentation/opencensus-proto/gen-go/metricsproto"
import traceproto "github.com/census-instrumentation/opencensus-proto/gen-go/traceproto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DumpSpanRequest struct {
	Spans                []*traceproto.Span `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *DumpSpanRequest) Reset()         { *m = DumpSpanRequest{} }
func (m *DumpSpanRequest) String() string { return proto.CompactTextString(m) }
func (*DumpSpanRequest) ProtoMessage()    {}
func (*DumpSpanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dump_cf0a434c0968e1dd, []int{0}
}
func (m *DumpSpanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpSpanRequest.Unmarshal(m, b)
}
func (m *DumpSpanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpSpanRequest.Marshal(b, m, deterministic)
}
func (dst *DumpSpanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpSpanRequest.Merge(dst, src)
}
func (m *DumpSpanRequest) XXX_Size() int {
	return xxx_messageInfo_DumpSpanRequest.Size(m)
}
func (m *DumpSpanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpSpanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DumpSpanRequest proto.InternalMessageInfo

func (m *DumpSpanRequest) GetSpans() []*traceproto.Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

type DumpSpanResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpSpanResponse) Reset()         { *m = DumpSpanResponse{} }
func (m *DumpSpanResponse) String() string { return proto.CompactTextString(m) }
func (*DumpSpanResponse) ProtoMessage()    {}
func (*DumpSpanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dump_cf0a434c0968e1dd, []int{1}
}
func (m *DumpSpanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpSpanResponse.Unmarshal(m, b)
}
func (m *DumpSpanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpSpanResponse.Marshal(b, m, deterministic)
}
func (dst *DumpSpanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpSpanResponse.Merge(dst, src)
}
func (m *DumpSpanResponse) XXX_Size() int {
	return xxx_messageInfo_DumpSpanResponse.Size(m)
}
func (m *DumpSpanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpSpanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DumpSpanResponse proto.InternalMessageInfo

type DumpMetricsRequest struct {
	Metrics              []*metricsproto.Metric `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DumpMetricsRequest) Reset()         { *m = DumpMetricsRequest{} }
func (m *DumpMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*DumpMetricsRequest) ProtoMessage()    {}
func (*DumpMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dump_cf0a434c0968e1dd, []int{2}
}
func (m *DumpMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpMetricsRequest.Unmarshal(m, b)
}
func (m *DumpMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpMetricsRequest.Marshal(b, m, deterministic)
}
func (dst *DumpMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpMetricsRequest.Merge(dst, src)
}
func (m *DumpMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_DumpMetricsRequest.Size(m)
}
func (m *DumpMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DumpMetricsRequest proto.InternalMessageInfo

func (m *DumpMetricsRequest) GetMetrics() []*metricsproto.Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type DumpMetricsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DumpMetricsResponse) Reset()         { *m = DumpMetricsResponse{} }
func (m *DumpMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*DumpMetricsResponse) ProtoMessage()    {}
func (*DumpMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dump_cf0a434c0968e1dd, []int{3}
}
func (m *DumpMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DumpMetricsResponse.Unmarshal(m, b)
}
func (m *DumpMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DumpMetricsResponse.Marshal(b, m, deterministic)
}
func (dst *DumpMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DumpMetricsResponse.Merge(dst, src)
}
func (m *DumpMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_DumpMetricsResponse.Size(m)
}
func (m *DumpMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DumpMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DumpMetricsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DumpSpanRequest)(nil), "hunter.proto.dump.DumpSpanRequest")
	proto.RegisterType((*DumpSpanResponse)(nil), "hunter.proto.dump.DumpSpanResponse")
	proto.RegisterType((*DumpMetricsRequest)(nil), "hunter.proto.dump.DumpMetricsRequest")
	proto.RegisterType((*DumpMetricsResponse)(nil), "hunter.proto.dump.DumpMetricsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DumpClient is the client API for Dump service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DumpClient interface {
	ExportSpan(ctx context.Context, opts ...grpc.CallOption) (Dump_ExportSpanClient, error)
	ExportMetrics(ctx context.Context, opts ...grpc.CallOption) (Dump_ExportMetricsClient, error)
}

type dumpClient struct {
	cc *grpc.ClientConn
}

func NewDumpClient(cc *grpc.ClientConn) DumpClient {
	return &dumpClient{cc}
}

func (c *dumpClient) ExportSpan(ctx context.Context, opts ...grpc.CallOption) (Dump_ExportSpanClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Dump_serviceDesc.Streams[0], "/hunter.proto.dump.Dump/ExportSpan", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpExportSpanClient{stream}
	return x, nil
}

type Dump_ExportSpanClient interface {
	Send(*DumpSpanRequest) error
	Recv() (*DumpSpanResponse, error)
	grpc.ClientStream
}

type dumpExportSpanClient struct {
	grpc.ClientStream
}

func (x *dumpExportSpanClient) Send(m *DumpSpanRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpExportSpanClient) Recv() (*DumpSpanResponse, error) {
	m := new(DumpSpanResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *dumpClient) ExportMetrics(ctx context.Context, opts ...grpc.CallOption) (Dump_ExportMetricsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Dump_serviceDesc.Streams[1], "/hunter.proto.dump.Dump/ExportMetrics", opts...)
	if err != nil {
		return nil, err
	}
	x := &dumpExportMetricsClient{stream}
	return x, nil
}

type Dump_ExportMetricsClient interface {
	Send(*DumpMetricsRequest) error
	Recv() (*DumpMetricsResponse, error)
	grpc.ClientStream
}

type dumpExportMetricsClient struct {
	grpc.ClientStream
}

func (x *dumpExportMetricsClient) Send(m *DumpMetricsRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dumpExportMetricsClient) Recv() (*DumpMetricsResponse, error) {
	m := new(DumpMetricsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DumpServer is the server API for Dump service.
type DumpServer interface {
	ExportSpan(Dump_ExportSpanServer) error
	ExportMetrics(Dump_ExportMetricsServer) error
}

func RegisterDumpServer(s *grpc.Server, srv DumpServer) {
	s.RegisterService(&_Dump_serviceDesc, srv)
}

func _Dump_ExportSpan_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServer).ExportSpan(&dumpExportSpanServer{stream})
}

type Dump_ExportSpanServer interface {
	Send(*DumpSpanResponse) error
	Recv() (*DumpSpanRequest, error)
	grpc.ServerStream
}

type dumpExportSpanServer struct {
	grpc.ServerStream
}

func (x *dumpExportSpanServer) Send(m *DumpSpanResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpExportSpanServer) Recv() (*DumpSpanRequest, error) {
	m := new(DumpSpanRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Dump_ExportMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DumpServer).ExportMetrics(&dumpExportMetricsServer{stream})
}

type Dump_ExportMetricsServer interface {
	Send(*DumpMetricsResponse) error
	Recv() (*DumpMetricsRequest, error)
	grpc.ServerStream
}

type dumpExportMetricsServer struct {
	grpc.ServerStream
}

func (x *dumpExportMetricsServer) Send(m *DumpMetricsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dumpExportMetricsServer) Recv() (*DumpMetricsRequest, error) {
	m := new(DumpMetricsRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Dump_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hunter.proto.dump.Dump",
	HandlerType: (*DumpServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportSpan",
			Handler:       _Dump_ExportSpan_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ExportMetrics",
			Handler:       _Dump_ExportMetrics_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/dump.proto",
}

func init() { proto.RegisterFile("proto/dump.proto", fileDescriptor_dump_cf0a434c0968e1dd) }

var fileDescriptor_dump_cf0a434c0968e1dd = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x0d, 0xfe, 0xc3, 0x11, 0xb1, 0xae, 0x0a, 0x12, 0x3c, 0x94, 0x88, 0xa5, 0x97, 0x24,
	0x52, 0x6f, 0xde, 0x2c, 0xf6, 0x28, 0x94, 0x7a, 0xd3, 0x53, 0x9a, 0x4e, 0xd3, 0x82, 0xd9, 0x59,
	0xf7, 0x0f, 0xe8, 0x47, 0xf4, 0x5b, 0xc9, 0x66, 0x12, 0x62, 0x0d, 0xea, 0x25, 0x9b, 0xdd, 0xbc,
	0xf7, 0x7b, 0x6f, 0x96, 0x40, 0x4f, 0x69, 0xb2, 0x94, 0x2e, 0x5c, 0xa9, 0x92, 0xea, 0x55, 0x9c,
	0xac, 0x9c, 0xb4, 0xa8, 0x79, 0x97, 0xf8, 0x0f, 0x61, 0x44, 0x0a, 0x65, 0x8e, 0xd2, 0x38, 0x93,
	0xb2, 0xde, 0xea, 0x2c, 0x47, 0x7e, 0xb2, 0x30, 0x1c, 0x74, 0x34, 0x25, 0x5a, 0xbd, 0xce, 0x4d,
	0xb3, 0xb2, 0x2e, 0x9a, 0xc0, 0xf1, 0x83, 0x2b, 0xd5, 0x93, 0xca, 0xe4, 0x0c, 0xdf, 0x1c, 0x1a,
	0x2b, 0x46, 0xb0, 0x6b, 0x54, 0x26, 0xcd, 0x45, 0xd0, 0xdf, 0x1e, 0x1e, 0x8e, 0x2e, 0x93, 0x16,
	0x55, 0xb7, 0xe0, 0xa0, 0xca, 0xc3, 0xd2, 0x48, 0x40, 0xaf, 0xc5, 0x18, 0x45, 0xd2, 0x60, 0x34,
	0x05, 0xe1, 0xcf, 0x1e, 0x39, 0xaf, 0xa1, 0xdf, 0xc1, 0x7e, 0xdd, 0xa0, 0xe6, 0xf7, 0xbb, 0xfc,
	0xa6, 0x22, 0x5b, 0x67, 0x8d, 0x21, 0x3a, 0x87, 0xd3, 0x0d, 0x22, 0x07, 0x8d, 0x3e, 0x03, 0xd8,
	0xf1, 0xe7, 0xe2, 0x05, 0x60, 0xf2, 0xae, 0x48, 0x5b, 0xdf, 0x43, 0x44, 0x49, 0xe7, 0xea, 0x92,
	0x1f, 0xb3, 0x86, 0x57, 0x7f, 0x6a, 0xea, 0x41, 0xb6, 0x86, 0xc1, 0x4d, 0x20, 0x16, 0x70, 0xc4,
	0xf0, 0x3a, 0x5e, 0x5c, 0xff, 0xe2, 0xdd, 0x1c, 0x38, 0x1c, 0xfc, 0x27, 0xfb, 0x9e, 0x32, 0x5e,
	0xc2, 0xd9, 0x9a, 0xba, 0x8e, 0xf1, 0x81, 0xb7, 0x4c, 0xfd, 0x7e, 0x1a, 0x3c, 0xdf, 0x17, 0x6b,
	0xbb, 0x72, 0xf3, 0x24, 0xa7, 0x32, 0x2d, 0x89, 0x88, 0x96, 0xaf, 0x1f, 0x69, 0x7b, 0x8b, 0x71,
	0x41, 0x31, 0x56, 0x55, 0x51, 0xc7, 0x59, 0x81, 0xd2, 0xa6, 0x05, 0xca, 0xb8, 0xe0, 0xff, 0xaa,
	0x82, 0xce, 0xf7, 0xaa, 0xe5, 0xf6, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x12, 0xa3, 0xc6, 0x00, 0x71,
	0x02, 0x00, 0x00,
}
